package the.pixel.factory.hmi;

import android.animation.ObjectAnimator;
import android.content.Intent;
import android.media.MediaPlayer;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;

public class Splash extends AppCompatActivity {
MediaPlayer clickSound;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_splash);
        clickSound = MediaPlayer.create(this, R.raw.intro_bgm);
        clickSound.start();
        clickSound.setLooping(true);
        ObjectAnimator a1 = ObjectAnimator.ofFloat(findViewById(R.id.l11), "rotationX", -180, 0);
        a1.setDuration(1500);
        a1.start();
        ObjectAnimator a2 = ObjectAnimator.ofFloat(findViewById(R.id.l12), "rotationX", -180, 0);
        a2.setStartDelay(200);
        a2.setDuration(1500);
        a2.start();
        ObjectAnimator a3 = ObjectAnimator.ofFloat(findViewById(R.id.l13), "rotationX", -180, 0);
        a3.setStartDelay(400);
        a3.setDuration(1500);
        a3.start();
        ObjectAnimator a4 = ObjectAnimator.ofFloat(findViewById(R.id.l14), "rotationX", -180, 0);
        a4.setStartDelay(600);
        a4.setDuration(1500);
        a4.start();
        ObjectAnimator a5 = ObjectAnimator.ofFloat(findViewById(R.id.l15), "rotationX", -180, 0);
        a5.setStartDelay(800);
        a5.setDuration(1500);
        a5.start();
        ObjectAnimator a6 = ObjectAnimator.ofFloat(findViewById(R.id.l16), "rotationX", -180, 0);
        a6.setStartDelay(1000);
        a6.setDuration(1500);
        a6.start();
        ObjectAnimator a7 = ObjectAnimator.ofFloat(findViewById(R.id.l17), "rotationX", -180, 0);
        a7.setStartDelay(1200);
        a7.setDuration(1500);
        a7.start();
        ObjectAnimator a8 = ObjectAnimator.ofFloat(findViewById(R.id.l18), "rotationX", -180, 0);
        a8.setStartDelay(1400);
        a8.setDuration(1500);
        a8.start();
        ObjectAnimator a9 = ObjectAnimator.ofFloat(findViewById(R.id.l19), "rotationX", -180, 0);
        a9.setStartDelay(1600);
        a9.setDuration(1500);
        a9.start();

        ObjectAnimator a10 = ObjectAnimator.ofFloat(findViewById(R.id.l21), "rotationX", -180, 0);
        a10.setStartDelay(600);
        a10.setDuration(1500);
        a10.start();
        ObjectAnimator a11 = ObjectAnimator.ofFloat(findViewById(R.id.l22), "rotationX", -180, 0);
        a11.setStartDelay(800);
        a11.setDuration(1500);
        a11.start();
        ObjectAnimator a12 = ObjectAnimator.ofFloat(findViewById(R.id.l23), "rotationX", -180, 0);
        a12.setStartDelay(1000);
        a12.setDuration(1500);
        a12.start();
        ObjectAnimator a13 = ObjectAnimator.ofFloat(findViewById(R.id.l24), "rotationX", -180, 0);
        a13.setStartDelay(1200);
        a13.setDuration(1500);
        a13.start();
        ObjectAnimator a14 = ObjectAnimator.ofFloat(findViewById(R.id.l25), "rotationX", -180, 0);
        a14.setStartDelay(1400);
        a14.setDuration(1500);
        a14.start();
        ObjectAnimator a15 = ObjectAnimator.ofFloat(findViewById(R.id.l26), "rotationX", -180, 0);
        a15.setStartDelay(1600);
        a15.setDuration(1500);
        a15.start();
        ObjectAnimator a16 = ObjectAnimator.ofFloat(findViewById(R.id.l27), "rotationX", -180, 0);
        a16.setStartDelay(1800);
        a16.setDuration(1500);
        a16.start();
        ObjectAnimator a17 = ObjectAnimator.ofFloat(findViewById(R.id.l28), "rotationX", -180, 0);
        a17.setStartDelay(2000);
        a17.setDuration(1500);
        a17.start();
        ObjectAnimator a18 = ObjectAnimator.ofFloat(findViewById(R.id.l29), "rotationX", -180, 0);
        a18.setStartDelay(2200);
        a18.setDuration(1500);
        a18.start();

        ObjectAnimator a19 = ObjectAnimator.ofFloat(findViewById(R.id.l31), "rotationX", -180, 0);
        a19.setStartDelay(1000);
        a19.setDuration(1500);
        a19.start();
        ObjectAnimator a20 = ObjectAnimator.ofFloat(findViewById(R.id.l32), "rotationX", -180, 0);
        a20.setStartDelay(1200);
        a20.setDuration(1500);
        a20.start();
        ObjectAnimator a21 = ObjectAnimator.ofFloat(findViewById(R.id.l33), "rotationX", -180, 0);
        a21.setStartDelay(1400);
        a21.setDuration(1500);
        a21.start();
        ObjectAnimator a22 = ObjectAnimator.ofFloat(findViewById(R.id.l34), "rotationX", -180, 0);
        a22.setStartDelay(1600);
        a22.setDuration(1500);
        a22.start();
        ObjectAnimator a23 = ObjectAnimator.ofFloat(findViewById(R.id.l35), "rotationX", -180, 0);
        a23.setStartDelay(1800);
        a23.setDuration(1500);
        a23.start();
        ObjectAnimator a24 = ObjectAnimator.ofFloat(findViewById(R.id.l36), "rotationX", -180, 0);
        a24.setStartDelay(2000);
        a24.setDuration(1500);
        a24.start();
        ObjectAnimator a25 = ObjectAnimator.ofFloat(findViewById(R.id.l37), "rotationX", -180, 0);
        a25.setStartDelay(2200);
        a25.setDuration(1500);
        a25.start();
        ObjectAnimator a26 = ObjectAnimator.ofFloat(findViewById(R.id.l38), "rotationX", -180, 0);
        a26.setStartDelay(2400);
        a26.setDuration(1500);
        a26.start();
        ObjectAnimator a27 = ObjectAnimator.ofFloat(findViewById(R.id.l39), "rotationX", -180, 0);
        a27.setStartDelay(2600);
        a27.setDuration(1500);
        a27.start();

        ObjectAnimator a28 = ObjectAnimator.ofFloat(findViewById(R.id.l41), "rotationX", -180, 0);
        a28.setStartDelay(1400);
        a28.setDuration(1500);
        a28.start();
        ObjectAnimator a29 = ObjectAnimator.ofFloat(findViewById(R.id.l42), "rotationX", -180, 0);
        a29.setStartDelay(1600);
        a29.setDuration(1500);
        a29.start();
        ObjectAnimator a30 = ObjectAnimator.ofFloat(findViewById(R.id.l43), "rotationX", -180, 0);
        a30.setStartDelay(1800);
        a30.setDuration(1500);
        a30.start();
        ObjectAnimator a31 = ObjectAnimator.ofFloat(findViewById(R.id.l44), "rotationX", -180, 0);
        a31.setStartDelay(2000);
        a31.setDuration(1500);
        a31.start();
        ObjectAnimator a32 = ObjectAnimator.ofFloat(findViewById(R.id.l45), "rotationX", -180, 0);
        a32.setStartDelay(2200);
        a32.setDuration(1500);
        a32.start();
        ObjectAnimator a33 = ObjectAnimator.ofFloat(findViewById(R.id.l46), "rotationX", -180, 0);
        a33.setStartDelay(2400);
        a33.setDuration(1500);
        a33.start();
        ObjectAnimator a34 = ObjectAnimator.ofFloat(findViewById(R.id.l47), "rotationX", -180, 0);
        a34.setStartDelay(2600);
        a34.setDuration(1500);
        a34.start();
        ObjectAnimator a35 = ObjectAnimator.ofFloat(findViewById(R.id.l48), "rotationX", -180, 0);
        a35.setStartDelay(2800);
        a35.setDuration(1500);
        a35.start();
        ObjectAnimator a36 = ObjectAnimator.ofFloat(findViewById(R.id.l49), "rotationX", -180, 0);
        a36.setStartDelay(3000);
        a36.setDuration(1500);
        a36.start();

        ObjectAnimator a37 = ObjectAnimator.ofFloat(findViewById(R.id.l51), "rotationX", -180, 0);
        a37.setStartDelay(1800);
        a37.setDuration(1500);
        a37.start();
        ObjectAnimator a38 = ObjectAnimator.ofFloat(findViewById(R.id.l52), "rotationX", -180, 0);
        a38.setStartDelay(2000);
        a38.setDuration(1500);
        a38.start();
        ObjectAnimator a39 = ObjectAnimator.ofFloat(findViewById(R.id.l53), "rotationX", -180, 0);
        a39.setStartDelay(2200);
        a39.setDuration(1500);
        a39.start();
        ObjectAnimator a40 = ObjectAnimator.ofFloat(findViewById(R.id.l54), "rotationX", -180, 0);
        a40.setStartDelay(2400);
        a40.setDuration(1500);
        a40.start();
        ObjectAnimator a41 = ObjectAnimator.ofFloat(findViewById(R.id.l55), "rotationX", -180, 0);
        a41.setStartDelay(2600);
        a41.setDuration(1500);
        a41.start();
        ObjectAnimator a42 = ObjectAnimator.ofFloat(findViewById(R.id.l56), "rotationX", -180, 0);
        a42.setStartDelay(2800);
        a42.setDuration(1500);
        a42.start();
        ObjectAnimator a43 = ObjectAnimator.ofFloat(findViewById(R.id.l57), "rotationX", -180, 0);
        a43.setStartDelay(3000);
        a43.setDuration(1500);
        a43.start();
        ObjectAnimator a44 = ObjectAnimator.ofFloat(findViewById(R.id.l58), "rotationX", -180, 0);
        a44.setStartDelay(3200);
        a44.setDuration(1500);
        a44.start();
        ObjectAnimator a45 = ObjectAnimator.ofFloat(findViewById(R.id.l59), "rotationX", -180, 0);
        a45.setStartDelay(3400);
        a45.setDuration(1500);
        a45.start();

        ObjectAnimator animator1 = ObjectAnimator.ofFloat(findViewById(R.id.tv1),"alpha", 0,1);
        //animator1.setStartDelay(1000);
        animator1.setDuration(4500);
        animator1.start();
        //findViewById(R.id.tv1).setVisibility(View.VISIBLE);
        ObjectAnimator animator2 = ObjectAnimator.ofFloat(findViewById(R.id.tv2),"alpha", 0,1);
        //animator2.setStartDelay(1200);
        animator2.setDuration(4700);
        animator2.start();
        //findViewById(R.id.tv2).setVisibility(View.VISIBLE);
        ObjectAnimator animator3 = ObjectAnimator.ofFloat(findViewById(R.id.tv3),"alpha", 0,1);
        //animator3.setStartDelay(1400);
        animator3.setDuration(4900);
        animator3.start();
        //findViewById(R.id.tv3).setVisibility(View.VISIBLE);
        ObjectAnimator animator4 = ObjectAnimator.ofFloat(findViewById(R.id.tv4),"alpha", 0,1);
        //animator4.setStartDelay(1600);
        animator4.setDuration(5100);
        animator4.start();
        //findViewById(R.id.tv4).setVisibility(View.VISIBLE);
        ObjectAnimator animator5 = ObjectAnimator.ofFloat(findViewById(R.id.tv5),"alpha", 0,1);
        //animator5.setStartDelay(1800);
        animator5.setDuration(5300);
        animator5.start();
        //findViewById(R.id.tv5).setVisibility(View.VISIBLE);
        ObjectAnimator animator6 = ObjectAnimator.ofFloat(findViewById(R.id.tv6),"alpha", 0,1);
        //animator6.setStartDelay(2000);
        animator6.setDuration(5500);
        animator6.start();
        //findViewById(R.id.tv6).setVisibility(View.VISIBLE);
        ObjectAnimator animator7 = ObjectAnimator.ofFloat(findViewById(R.id.tv7),"alpha", 0,1);
        //animator7.setStartDelay(2200);
        animator7.setDuration(5700);
        animator7.start();
        //findViewById(R.id.tv7).setVisibility(View.VISIBLE);
        ObjectAnimator animator8 = ObjectAnimator.ofFloat(findViewById(R.id.tv8),"alpha", 0,1);
        //animator8.setStartDelay(2400);
        animator8.setDuration(5900);
        animator8.start();
        //findViewById(R.id.tv8).setVisibility(View.VISIBLE);
        ObjectAnimator animator9 = ObjectAnimator.ofFloat(findViewById(R.id.tv9),"alpha", 0,1);
        //animator9.setStartDelay(2600);
        animator9.setDuration(5600);
        animator9.start();
        //findViewById(R.id.tv9).setVisibility(View.VISIBLE);

        Thread logoTimer = new Thread() {
            public void run() {
                try {
                    sleep(6000);
                    Intent menuIntent = new Intent(Splash.this,Start.class);
                    startActivity(menuIntent);
                    finish();


                } catch (InterruptedException e) {
                    e.printStackTrace();
                } finally {
                    finish();
                }


            }
        };
        logoTimer.start();
    }
}
